apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: test-cluster-0
  labels:
    ray.io/scheduler-name: volcano
    volcano.sh/queue-name: kuberay-test-queue
spec:
  rayVersion: '2.7.0'
  headGroupSpec:
    rayStartParams: {}
    replicas: 1
    template:
      spec:
        containers:
        - name: ray-head
          image: quay.apps.mgmt1.ocp.trafikverket.local/registry-1.docker.io/rayproject/ray:2.7.0
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
  workerGroupSpecs:
    - groupName: worker
      rayStartParams: {}
      replicas: 2
      minReplicas: 2
      maxReplicas: 2
      template:
        spec:
          containers:
          - name: ray-head
            image: quay.apps.mgmt1.ocp.trafikverket.local/registry-1.docker.io/rayproject/ray:2.7.0
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "1"
                memory: "1Gi"
